# Generated by Django 4.0.5 on 2022-06-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_link_options_rename_literal_link_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
