# Generated by Django 4.0.5 on 2022-08-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_dir',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
