# Generated by Django 4.0.5 on 2022-10-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_category_page_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=255)),
                ('expert_name', models.CharField(max_length=255)),
                ('expert_email', models.EmailField(max_length=255)),
                ('message', models.TextField(null=True)),
                ('response', models.TextField(default=None, null=True)),
                ('state', models.CharField(choices=[('RR', 'Request received'), ('ES', 'Email sent to expert'), ('ER', 'Email response received from expert'), ('PU', 'Page updated')], default='RR', max_length=2)),
            ],
            options={
                'ordering': ['page_title', 'pk'],
            },
        ),
    ]
